FROM golang:1.24-alpine AS builder

WORKDIR /app

# Install 'fresh' for hot-reloading
RUN go install github.com/gravityblast/fresh@latest

# Copy go.mod and go.sum first to cache dependencies
COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

EXPOSE 8080

# The command to run the application with fresh will be in docker-compose.yml
# CMD ["fresh"] # This will be overridden by the 'command' in docker-compose.yml