// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Entry struct {
	ID           int64
	TierlistUuid string
	TierID       *int64
	FileKey      string
	Order        int64
}

type Tier struct {
	ID           int64
	TierlistUuid string
	Name         string
	Order        int64
}

type Tierlist struct {
	Uuid string
	Name string
}
